this is a note book for discovring source data and mini analysis

In [2]:
%pip install boto3 pandas

Collecting boto3
  Downloading boto3-1.43.77-py3-none-any.whl (140 kB)
Collecting pandas
  Downloading pandas-2.3.3-cp310-cp310-win_amd64.whl (11.3 MB)
Collecting botocore<1.44.0,>=1.43.77
  Downloading botocore-1.43.77-py3-none-any.whl (15.7 MB)
Collecting jmespath<2.0.0,>=0.7.1
  Downloading jmespath-1.1.0-py3-none-any.whl (20 kB)
Collecting s3transfer<0.20.0,>=0.19.0
  Downloading s3transfer-0.19.2-py3-none-any.whl (90 kB)
Collecting numpy>=1.22.4
  Downloading numpy-2.2.6-cp310-cp310-win_amd64.whl (12.9 MB)
Collecting pytz>=2020.1
  Downloading pytz-2026.3.post1-py2.py3-none-any.whl (508 kB)
Collecting tzdata>=2022.7
  Downloading tzdata-2026.3-py2.py3-none-any.whl (348 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\programdata\anaconda3\envs\pythonproject\lib\site-packages (from pandas) (2.9.0.post0)
Collecting urllib3!=2.2.0,<3,>=1.25.4
  Downloading urllib3-2.7.0-py3-none-any.whl (131 kB)
Requirement already satisfied: six>=1.5 in c:\programdata\anaconda3\envs\pythonproject\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Installing collected packages: urllib3, jmespath, botocore, tzdata, s3transfer, pytz, numpy, pandas, boto3
Successfully installed boto3-1.43.77 botocore-1.43.77 jmespath-1.1.0 numpy-2.2.6 pandas-2.3.3 pytz-2026.3.post1 s3transfer-0.19.2 tzdata-2026.3 urllib3-2.7.0
Note: you may need to restart the kernel to use updated packages.

In [10]:
import boto3
import pandas as pd

BUCKET = "cct-ds-code-challenge-input-data"
REGION = "af-south-1"

s3 = boto3.client(
    "s3",
    region_name=REGION
)

In [ ]:
response = s3.list_objects_v2(Bucket=BUCKET)

for file in response["Contents"]:
    print(file["Key"])

city-hex-polygons-7.geojson
city-hex-polygons-8-10.geojson
city-hex-polygons-8.geojson
ds_code_challenge_creds.json
images/swimming-pool/no/W07C_11_100.tif
images/swimming-pool/no/W07C_11_61.tif
images/swimming-pool/no/W07C_11_71.tif
images/swimming-pool/no/W07C_11_82.tif
images/swimming-pool/no/W07C_11_88.tif
images/swimming-pool/no/W07C_11_97.tif
images/swimming-pool/no/W07C_16_1.tif
images/swimming-pool/no/W07C_16_10.tif
images/swimming-pool/no/W07C_16_17.tif
images/swimming-pool/no/W07C_16_24.tif
images/swimming-pool/no/W07C_16_25.tif
images/swimming-pool/no/W07C_16_27.tif
images/swimming-pool/no/W07C_16_29.tif
images/swimming-pool/no/W07C_16_35.tif
images/swimming-pool/no/W07C_16_36.tif
images/swimming-pool/no/W07C_16_38.tif
images/swimming-pool/no/W07C_16_39.tif
images/swimming-pool/no/W07C_16_40.tif
images/swimming-pool/no/W07C_16_45.tif
images/swimming-pool/no/W07C_16_46.tif
images/swimming-pool/no/W07C_16_47.tif
images/swimming-pool/no/W07C_16_5.tif
images/swimming-pool/no/W07C_16_52.tif
images/swimming-pool/no/W07C_16_53.tif
images/swimming-pool/no/W07C_16_6.tif
images/swimming-pool/no/W07C_16_62.tif
images/swimming-pool/no/W07C_16_64.tif
images/swimming-pool/no/W07C_16_67.tif
images/swimming-pool/no/W07C_16_68.tif
images/swimming-pool/no/W07C_16_78.tif
images/swimming-pool/no/W07C_16_82.tif
images/swimming-pool/no/W07C_16_83.tif
images/swimming-pool/no/W07C_16_84.tif
images/swimming-pool/no/W07C_16_86.tif
images/swimming-pool/no/W07C_16_88.tif
images/swimming-pool/no/W07C_16_93.tif
images/swimming-pool/no/W07C_16_96.tif
images/swimming-pool/no/W07C_16_97.tif
images/swimming-pool/no/W07C_17_13.tif
images/swimming-pool/no/W07C_17_21.tif
images/swimming-pool/no/W07C_17_31.tif
images/swimming-pool/no/W07C_21_13.tif
images/swimming-pool/no/W07C_21_17.tif
images/swimming-pool/no/W07C_21_22.tif
images/swimming-pool/no/W07C_21_23.tif
images/swimming-pool/no/W07C_21_26.tif
images/swimming-pool/no/W07C_21_42.tif
images/swimming-pool/no/W07C_21_44.tif
images/swimming-pool/no/W07C_21_51.tif
images/swimming-pool/no/W07C_21_52.tif
images/swimming-pool/no/W07C_21_53.tif
images/swimming-pool/no/W07C_21_7.tif
images/swimming-pool/no/W07C_21_71.tif
images/swimming-pool/no/W16C_17_100.tif
images/swimming-pool/no/W16C_17_99.tif
images/swimming-pool/no/W16C_18_100.tif
images/swimming-pool/no/W16C_18_60.tif
images/swimming-pool/no/W16C_18_70.tif
images/swimming-pool/no/W16C_18_78.tif
images/swimming-pool/no/W16C_18_79.tif
images/swimming-pool/no/W16C_18_89.tif
images/swimming-pool/no/W16C_18_96.tif
images/swimming-pool/no/W16C_19_13.tif
images/swimming-pool/no/W16C_19_22.tif
images/swimming-pool/no/W16C_19_23.tif
images/swimming-pool/no/W16C_19_25.tif
images/swimming-pool/no/W16C_19_34.tif
images/swimming-pool/no/W16C_19_35.tif
images/swimming-pool/no/W16C_19_41.tif
images/swimming-pool/no/W16C_19_43.tif
images/swimming-pool/no/W16C_19_44.tif
images/swimming-pool/no/W16C_19_45.tif
images/swimming-pool/no/W16C_19_46.tif
images/swimming-pool/no/W16C_19_49.tif
images/swimming-pool/no/W16C_19_50.tif
images/swimming-pool/no/W16C_19_59.tif
images/swimming-pool/no/W16C_19_65.tif
images/swimming-pool/no/W16C_19_67.tif
images/swimming-pool/no/W16C_19_69.tif
images/swimming-pool/no/W16C_19_72.tif
images/swimming-pool/no/W16C_19_74.tif
images/swimming-pool/no/W16C_19_77.tif
images/swimming-pool/no/W16C_19_80.tif
images/swimming-pool/no/W16C_19_82.tif
images/swimming-pool/no/W16C_19_83.tif
images/swimming-pool/no/W16C_19_84.tif
images/swimming-pool/no/W16C_19_90.tif
images/swimming-pool/no/W16C_20_51.tif
images/swimming-pool/no/W16C_20_71.tif
images/swimming-pool/no/W16C_20_81.tif
images/swimming-pool/no/W16C_20_92.tif
images/swimming-pool/no/W16C_22_28.tif
images/swimming-pool/no/W16C_22_40.tif
images/swimming-pool/no/W16C_22_9.tif
images/swimming-pool/no/W16C_23_12.tif
images/swimming-pool/no/W16C_23_15.tif
images/swimming-pool/no/W16C_23_17.tif
images/swimming-pool/no/W16C_23_22.tif
images/swimming-pool/no/W16C_23_24.tif
images/swimming-pool/no/W16C_23_27.tif
images/swimming-pool/no/W16C_23_7.tif
images/swimming-pool/no/W16C_23_99.tif
images/swimming-pool/no/W16C_24_12.tif
images/swimming-pool/no/W16C_24_15.tif
images/swimming-pool/no/W16C_24_20.tif
images/swimming-pool/no/W16C_24_3.tif
images/swimming-pool/no/W16C_25_1.tif
images/swimming-pool/no/W16C_25_11.tif
images/swimming-pool/no/W16C_25_12.tif
images/swimming-pool/no/W16C_25_22.tif
images/swimming-pool/no/W16C_25_32.tif
images/swimming-pool/no/W16C_25_35.tif
images/swimming-pool/no/W16C_25_50.tif
images/swimming-pool/no/W16C_25_53.tif
images/swimming-pool/no/W16C_25_60.tif
images/swimming-pool/no/W16C_25_96.tif
images/swimming-pool/no/W16D_21_51.tif
images/swimming-pool/no/W16D_22_100.tif
images/swimming-pool/no/W16D_22_15.tif
images/swimming-pool/no/W16D_22_24.tif
images/swimming-pool/no/W16D_22_44.tif
images/swimming-pool/no/W16D_22_6.tif
images/swimming-pool/no/W16D_22_71.tif
images/swimming-pool/no/W16D_23_92.tif
images/swimming-pool/no/W16D_25_92.tif
images/swimming-pool/no/W17A_10_16.tif
images/swimming-pool/no/W17A_10_26.tif
images/swimming-pool/no/W17A_10_29.tif
images/swimming-pool/no/W17A_10_33.tif
images/swimming-pool/no/W17A_10_34.tif
images/swimming-pool/no/W17A_10_39.tif
images/swimming-pool/no/W17A_10_42.tif
images/swimming-pool/no/W17A_10_43.tif
images/swimming-pool/no/W17A_10_54.tif
images/swimming-pool/no/W17A_10_90.tif
images/swimming-pool/no/W17A_13_9.tif
images/swimming-pool/no/W17A_14_100.tif
images/swimming-pool/no/W17A_14_60.tif
images/swimming-pool/no/W17A_14_68.tif
images/swimming-pool/no/W17A_14_77.tif
images/swimming-pool/no/W17A_14_85.tif
images/swimming-pool/no/W17A_15_10.tif
images/swimming-pool/no/W17A_15_20.tif
images/swimming-pool/no/W17A_15_43.tif
images/swimming-pool/no/W17A_15_51.tif
images/swimming-pool/no/W17A_15_52.tif
images/swimming-pool/no/W17A_15_53.tif
images/swimming-pool/no/W17A_15_64.tif
images/swimming-pool/no/W17A_15_72.tif
images/swimming-pool/no/W17A_15_75.tif
images/swimming-pool/no/W17A_15_76.tif
images/swimming-pool/no/W17A_15_77.tif
images/swimming-pool/no/W17A_15_78.tif
images/swimming-pool/no/W17A_15_80.tif
images/swimming-pool/no/W17A_15_81.tif
images/swimming-pool/no/W17A_15_82.tif
images/swimming-pool/no/W17A_15_84.tif
images/swimming-pool/no/W17A_15_87.tif
images/swimming-pool/no/W17A_15_89.tif
images/swimming-pool/no/W17A_15_92.tif
images/swimming-pool/no/W17A_15_94.tif
images/swimming-pool/no/W17A_15_95.tif
images/swimming-pool/no/W17A_15_97.tif
images/swimming-pool/no/W17A_18_80.tif
images/swimming-pool/no/W17A_18_86.tif
images/swimming-pool/no/W17A_19_16.tif
images/swimming-pool/no/W17A_19_18.tif
images/swimming-pool/no/W17A_19_26.tif
images/swimming-pool/no/W17A_19_27.tif
images/swimming-pool/no/W17A_19_37.tif
images/swimming-pool/no/W17A_19_40.tif
images/swimming-pool/no/W17A_19_46.tif
images/swimming-pool/no/W17A_19_47.tif
images/swimming-pool/no/W17A_19_49.tif
images/swimming-pool/no/W17A_19_50.tif
images/swimming-pool/no/W17A_19_54.tif
images/swimming-pool/no/W17A_19_55.tif
images/swimming-pool/no/W17A_19_56.tif
images/swimming-pool/no/W17A_19_61.tif
images/swimming-pool/no/W17A_19_62.tif
images/swimming-pool/no/W17A_19_63.tif
images/swimming-pool/no/W17A_19_68.tif
images/swimming-pool/no/W17A_19_73.tif
images/swimming-pool/no/W17A_19_74.tif
images/swimming-pool/no/W17A_19_76.tif
images/swimming-pool/no/W17A_19_79.tif
images/swimming-pool/no/W17A_19_8.tif
images/swimming-pool/no/W17A_19_83.tif
images/swimming-pool/no/W17A_19_86.tif
images/swimming-pool/no/W17A_19_91.tif
images/swimming-pool/no/W17A_19_94.tif
images/swimming-pool/no/W17A_19_96.tif
images/swimming-pool/no/W17A_19_99.tif
images/swimming-pool/no/W17A_20_10.tif
images/swimming-pool/no/W17A_20_13.tif
images/swimming-pool/no/W17A_20_16.tif
images/swimming-pool/no/W17A_20_18.tif
images/swimming-pool/no/W17A_20_24.tif
images/swimming-pool/no/W17A_20_25.tif
images/swimming-pool/no/W17A_20_26.tif
images/swimming-pool/no/W17A_20_28.tif
images/swimming-pool/no/W17A_20_29.tif
images/swimming-pool/no/W17A_20_30.tif
images/swimming-pool/no/W17A_20_31.tif
images/swimming-pool/no/W17A_20_33.tif
images/swimming-pool/no/W17A_20_37.tif
images/swimming-pool/no/W17A_20_38.tif
images/swimming-pool/no/W17A_20_39.tif
images/swimming-pool/no/W17A_20_43.tif
images/swimming-pool/no/W17A_20_46.tif
images/swimming-pool/no/W17A_20_48.tif
images/swimming-pool/no/W17A_20_49.tif
images/swimming-pool/no/W17A_20_5.tif
images/swimming-pool/no/W17A_20_52.tif
images/swimming-pool/no/W17A_20_57.tif
images/swimming-pool/no/W17A_20_60.tif
images/swimming-pool/no/W17A_20_64.tif
images/swimming-pool/no/W17A_20_66.tif
images/swimming-pool/no/W17A_20_69.tif
images/swimming-pool/no/W17A_20_73.tif
images/swimming-pool/no/W17A_20_74.tif
images/swimming-pool/no/W17A_20_81.tif
images/swimming-pool/no/W17A_20_85.tif
images/swimming-pool/no/W17A_20_87.tif
images/swimming-pool/no/W17A_20_89.tif
images/swimming-pool/no/W17A_20_91.tif
images/swimming-pool/no/W17A_20_93.tif
images/swimming-pool/no/W17A_20_94.tif
images/swimming-pool/no/W17A_20_97.tif
images/swimming-pool/no/W17A_23_40.tif
images/swimming-pool/no/W17A_23_90.tif
images/swimming-pool/no/W17A_24_11.tif
images/swimming-pool/no/W17A_24_12.tif
images/swimming-pool/no/W17A_24_18.tif
images/swimming-pool/no/W17A_24_2.tif
images/swimming-pool/no/W17A_24_26.tif
images/swimming-pool/no/W17A_24_30.tif
images/swimming-pool/no/W17A_24_33.tif
images/swimming-pool/no/W17A_24_34.tif
images/swimming-pool/no/W17A_24_35.tif
images/swimming-pool/no/W17A_24_36.tif
images/swimming-pool/no/W17A_24_47.tif
images/swimming-pool/no/W17A_24_51.tif
images/swimming-pool/no/W17A_24_54.tif
images/swimming-pool/no/W17A_24_55.tif
images/swimming-pool/no/W17A_24_6.tif
images/swimming-pool/no/W17A_24_61.tif
images/swimming-pool/no/W17A_24_62.tif
images/swimming-pool/no/W17A_24_65.tif
images/swimming-pool/no/W17A_24_7.tif
images/swimming-pool/no/W17A_24_71.tif
images/swimming-pool/no/W17A_24_73.tif
images/swimming-pool/no/W17A_24_75.tif
images/swimming-pool/no/W17A_24_87.tif
images/swimming-pool/no/W17A_25_1.tif
images/swimming-pool/no/W17A_25_100.tif
images/swimming-pool/no/W17A_25_11.tif
images/swimming-pool/no/W17A_25_2.tif
images/swimming-pool/no/W17A_25_21.tif
images/swimming-pool/no/W17A_25_26.tif
images/swimming-pool/no/W17A_3_19.tif
images/swimming-pool/no/W17A_3_20.tif
images/swimming-pool/no/W17A_3_28.tif
images/swimming-pool/no/W17A_3_56.tif
images/swimming-pool/no/W17A_3_85.tif
images/swimming-pool/no/W17A_4_100.tif
images/swimming-pool/no/W17A_4_17.tif
images/swimming-pool/no/W17A_4_27.tif
images/swimming-pool/no/W17A_4_8.tif
images/swimming-pool/no/W17A_5_100.tif
images/swimming-pool/no/W17A_5_25.tif
images/swimming-pool/no/W17A_5_3.tif
images/swimming-pool/no/W17A_5_52.tif
images/swimming-pool/no/W17A_8_100.tif
images/swimming-pool/no/W17A_8_4.tif
images/swimming-pool/no/W17A_8_47.tif
images/swimming-pool/no/W17A_8_49.tif
images/swimming-pool/no/W17A_8_50.tif
images/swimming-pool/no/W17A_8_59.tif
images/swimming-pool/no/W17A_8_69.tif
images/swimming-pool/no/W17A_8_70.tif
images/swimming-pool/no/W17A_8_80.tif
images/swimming-pool/no/W17A_8_89.tif
images/swimming-pool/no/W17A_8_99.tif
images/swimming-pool/no/W17A_9_18.tif
images/swimming-pool/no/W17A_9_19.tif
images/swimming-pool/no/W17A_9_26.tif
images/swimming-pool/no/W17A_9_27.tif
images/swimming-pool/no/W17A_9_28.tif
images/swimming-pool/no/W17A_9_29.tif
images/swimming-pool/no/W17A_9_39.tif
images/swimming-pool/no/W17A_9_46.tif
images/swimming-pool/no/W17A_9_48.tif
images/swimming-pool/no/W17A_9_50.tif
images/swimming-pool/no/W17A_9_51.tif
images/swimming-pool/no/W17A_9_57.tif
images/swimming-pool/no/W17A_9_61.tif
images/swimming-pool/no/W17A_9_62.tif
images/swimming-pool/no/W17A_9_63.tif
images/swimming-pool/no/W17A_9_67.tif
images/swimming-pool/no/W17A_9_71.tif
images/swimming-pool/no/W17A_9_72.tif
images/swimming-pool/no/W17A_9_75.tif
images/swimming-pool/no/W17A_9_76.tif
images/swimming-pool/no/W17A_9_79.tif
images/swimming-pool/no/W17A_9_81.tif
images/swimming-pool/no/W17A_9_82.tif
images/swimming-pool/no/W17A_9_83.tif
images/swimming-pool/no/W17A_9_93.tif
images/swimming-pool/no/W17B_10_11.tif
images/swimming-pool/no/W17B_10_13.tif
images/swimming-pool/no/W17B_10_85.tif
images/swimming-pool/no/W17B_10_86.tif
images/swimming-pool/no/W17B_11_17.tif
images/swimming-pool/no/W17B_11_18.tif
images/swimming-pool/no/W17B_11_19.tif
images/swimming-pool/no/W17B_11_28.tif
images/swimming-pool/no/W17B_11_41.tif
images/swimming-pool/no/W17B_11_43.tif
images/swimming-pool/no/W17B_11_44.tif
images/swimming-pool/no/W17B_11_45.tif
images/swimming-pool/no/W17B_11_47.tif
images/swimming-pool/no/W17B_11_51.tif
images/swimming-pool/no/W17B_11_59.tif
images/swimming-pool/no/W17B_11_60.tif
images/swimming-pool/no/W17B_11_62.tif
images/swimming-pool/no/W17B_11_63.tif
images/swimming-pool/no/W17B_11_73.tif
images/swimming-pool/no/W17B_11_79.tif
images/swimming-pool/no/W17B_11_80.tif
images/swimming-pool/no/W17B_11_86.tif
images/swimming-pool/no/W17B_11_87.tif
images/swimming-pool/no/W17B_11_88.tif
images/swimming-pool/no/W17B_11_89.tif
images/swimming-pool/no/W17B_11_91.tif
images/swimming-pool/no/W17B_11_92.tif
images/swimming-pool/no/W17B_11_93.tif
images/swimming-pool/no/W17B_12_18.tif
images/swimming-pool/no/W17B_12_19.tif
images/swimming-pool/no/W17B_12_30.tif
images/swimming-pool/no/W17B_12_41.tif
images/swimming-pool/no/W17B_12_61.tif
images/swimming-pool/no/W17B_12_62.tif
images/swimming-pool/no/W17B_12_63.tif
images/swimming-pool/no/W17B_12_65.tif
images/swimming-pool/no/W17B_12_72.tif
images/swimming-pool/no/W17B_12_73.tif
images/swimming-pool/no/W17B_12_74.tif
images/swimming-pool/no/W17B_12_75.tif
images/swimming-pool/no/W17B_12_81.tif
images/swimming-pool/no/W17B_12_82.tif
images/swimming-pool/no/W17B_12_83.tif
images/swimming-pool/no/W17B_12_84.tif
images/swimming-pool/no/W17B_12_92.tif
images/swimming-pool/no/W17B_12_93.tif
images/swimming-pool/no/W17B_12_96.tif
images/swimming-pool/no/W17B_12_97.tif
images/swimming-pool/no/W17B_13_12.tif
images/swimming-pool/no/W17B_13_21.tif
images/swimming-pool/no/W17B_13_39.tif
images/swimming-pool/no/W17B_13_49.tif
images/swimming-pool/no/W17B_13_50.tif
images/swimming-pool/no/W17B_13_84.tif
images/swimming-pool/no/W17B_13_86.tif
images/swimming-pool/no/W17B_13_88.tif
images/swimming-pool/no/W17B_13_93.tif
images/swimming-pool/no/W17B_13_94.tif
images/swimming-pool/no/W17B_13_95.tif
images/swimming-pool/no/W17B_14_36.tif
images/swimming-pool/no/W17B_14_47.tif
images/swimming-pool/no/W17B_14_50.tif
images/swimming-pool/no/W17B_14_52.tif
images/swimming-pool/no/W17B_14_58.tif
images/swimming-pool/no/W17B_14_61.tif
images/swimming-pool/no/W17B_14_63.tif
images/swimming-pool/no/W17B_14_64.tif
images/swimming-pool/no/W17B_15_41.tif
images/swimming-pool/no/W17B_15_51.tif
images/swimming-pool/no/W17B_16_1.tif
images/swimming-pool/no/W17B_16_13.tif
images/swimming-pool/no/W17B_16_16.tif
images/swimming-pool/no/W17B_16_17.tif
images/swimming-pool/no/W17B_16_18.tif
images/swimming-pool/no/W17B_16_2.tif
images/swimming-pool/no/W17B_16_20.tif
images/swimming-pool/no/W17B_16_22.tif
images/swimming-pool/no/W17B_16_23.tif
images/swimming-pool/no/W17B_16_25.tif
images/swimming-pool/no/W17B_16_28.tif
images/swimming-pool/no/W17B_16_30.tif
images/swimming-pool/no/W17B_16_35.tif
images/swimming-pool/no/W17B_16_37.tif
images/swimming-pool/no/W17B_16_38.tif
images/swimming-pool/no/W17B_16_4.tif
images/swimming-pool/no/W17B_16_42.tif
images/swimming-pool/no/W17B_16_47.tif
images/swimming-pool/no/W17B_16_48.tif
images/swimming-pool/no/W17B_16_5.tif
images/swimming-pool/no/W17B_16_54.tif
images/swimming-pool/no/W17B_16_56.tif
images/swimming-pool/no/W17B_16_59.tif
images/swimming-pool/no/W17B_16_63.tif
images/swimming-pool/no/W17B_16_64.tif
images/swimming-pool/no/W17B_16_66.tif
images/swimming-pool/no/W17B_16_8.tif
images/swimming-pool/no/W17B_16_84.tif
images/swimming-pool/no/W17B_16_92.tif
images/swimming-pool/no/W17B_16_94.tif
images/swimming-pool/no/W17B_16_97.tif
images/swimming-pool/no/W17B_16_99.tif
images/swimming-pool/no/W17B_17_12.tif
images/swimming-pool/no/W17B_17_15.tif
images/swimming-pool/no/W17B_17_16.tif
images/swimming-pool/no/W17B_17_18.tif
images/swimming-pool/no/W17B_17_2.tif
images/swimming-pool/no/W17B_17_30.tif
images/swimming-pool/no/W17B_17_32.tif
images/swimming-pool/no/W17B_17_35.tif
images/swimming-pool/no/W17B_17_37.tif
images/swimming-pool/no/W17B_17_54.tif
images/swimming-pool/no/W17B_17_57.tif
images/swimming-pool/no/W17B_17_67.tif
images/swimming-pool/no/W17B_17_70.tif
images/swimming-pool/no/W17B_17_86.tif
images/swimming-pool/no/W17B_17_90.tif
images/swimming-pool/no/W17B_17_93.tif
images/swimming-pool/no/W17B_17_95.tif
images/swimming-pool/no/W17B_18_11.tif
images/swimming-pool/no/W17B_18_19.tif
images/swimming-pool/no/W17B_18_27.tif
images/swimming-pool/no/W17B_18_28.tif
images/swimming-pool/no/W17B_18_29.tif
images/swimming-pool/no/W17B_18_3.tif
images/swimming-pool/no/W17B_18_31.tif
images/swimming-pool/no/W17B_18_38.tif
images/swimming-pool/no/W17B_18_4.tif
images/swimming-pool/no/W17B_18_40.tif
images/swimming-pool/no/W17B_18_41.tif
images/swimming-pool/no/W17B_18_48.tif
images/swimming-pool/no/W17B_18_49.tif
images/swimming-pool/no/W17B_18_5.tif
images/swimming-pool/no/W17B_18_52.tif
images/swimming-pool/no/W17B_18_58.tif
images/swimming-pool/no/W17B_18_6.tif
images/swimming-pool/no/W17B_18_61.tif
images/swimming-pool/no/W17B_18_94.tif
images/swimming-pool/no/W17B_19_11.tif
images/swimming-pool/no/W17B_19_21.tif
images/swimming-pool/no/W17B_19_41.tif
images/swimming-pool/no/W17B_1_72.tif
images/swimming-pool/no/W17B_1_77.tif
images/swimming-pool/no/W17B_1_87.tif
images/swimming-pool/no/W17B_1_97.tif
images/swimming-pool/no/W17B_21_15.tif
images/swimming-pool/no/W17B_21_19.tif
images/swimming-pool/no/W17B_21_23.tif
images/swimming-pool/no/W17B_21_24.tif
images/swimming-pool/no/W17B_21_27.tif
images/swimming-pool/no/W17B_21_29.tif
images/swimming-pool/no/W17B_21_3.tif
images/swimming-pool/no/W17B_21_33.tif
images/swimming-pool/no/W17B_21_4.tif
images/swimming-pool/no/W17B_21_47.tif
images/swimming-pool/no/W17B_21_5.tif
images/swimming-pool/no/W17B_21_54.tif
images/swimming-pool/no/W17B_21_58.tif
images/swimming-pool/no/W17B_21_60.tif
images/swimming-pool/no/W17B_21_67.tif
images/swimming-pool/no/W17B_21_68.tif
images/swimming-pool/no/W17B_21_69.tif
images/swimming-pool/no/W17B_21_7.tif
images/swimming-pool/no/W17B_21_76.tif
images/swimming-pool/no/W17B_21_78.tif
images/swimming-pool/no/W17B_21_81.tif
images/swimming-pool/no/W17B_21_86.tif
images/swimming-pool/no/W17B_21_87.tif
images/swimming-pool/no/W17B_21_92.tif
images/swimming-pool/no/W17B_21_93.tif
images/swimming-pool/no/W17B_21_96.tif
images/swimming-pool/no/W17B_21_97.tif
images/swimming-pool/no/W17B_22_1.tif
images/swimming-pool/no/W17B_22_15.tif
images/swimming-pool/no/W17B_22_2.tif
images/swimming-pool/no/W17B_22_20.tif
images/swimming-pool/no/W17B_22_28.tif
images/swimming-pool/no/W17B_22_61.tif
images/swimming-pool/no/W17B_22_63.tif
images/swimming-pool/no/W17B_22_67.tif
images/swimming-pool/no/W17B_22_71.tif
images/swimming-pool/no/W17B_22_77.tif
images/swimming-pool/no/W17B_22_78.tif
images/swimming-pool/no/W17B_22_84.tif
images/swimming-pool/no/W17B_22_86.tif
images/swimming-pool/no/W17B_22_88.tif
images/swimming-pool/no/W17B_22_89.tif
images/swimming-pool/no/W17B_22_92.tif
images/swimming-pool/no/W17B_22_94.tif
images/swimming-pool/no/W17B_22_96.tif
images/swimming-pool/no/W17B_23_2.tif
images/swimming-pool/no/W17B_23_22.tif
images/swimming-pool/no/W17B_23_34.tif
images/swimming-pool/no/W17B_23_43.tif
images/swimming-pool/no/W17B_23_45.tif
images/swimming-pool/no/W17B_23_53.tif
images/swimming-pool/no/W17B_23_54.tif
images/swimming-pool/no/W17B_23_55.tif
images/swimming-pool/no/W17B_23_56.tif
images/swimming-pool/no/W17B_23_64.tif
images/swimming-pool/no/W17B_23_66.tif
images/swimming-pool/no/W17B_23_67.tif
images/swimming-pool/no/W17B_23_70.tif

In [1]:
import boto3
import pandas as pd

BUCKET = "cct-ds-code-challenge-input-data"
REGION = "af-south-1"

s3 = boto3.client(
    "s3",
    region_name=REGION
)

response = s3.list_objects_v2(Bucket=BUCKET)

files = []

for obj in response.get("Contents", []):
    files.append({
        "key": obj["Key"],
        "size_bytes": obj["Size"],
        "last_modified": obj["LastModified"]
    })

files_df = pd.DataFrame(files)

files_df

,key,size_bytes,last_modified
0,city-hex-polygons-7.geojson,276231,2021-05-14 09:52:18+00:00
1,city-hex-polygons-8-10.geojson,108254980,2021-05-14 09:44:09+00:00
2,city-hex-polygons-8.geojson,1966685,2021-05-14 13:10:00+00:00
3,ds_code_challenge_creds.json,115,2021-05-14 16:34:40+00:00
4,images/swimming-pool/no/W07C_11_100.tif,3932696,2025-06-12 09:03:22+00:00
...,...,...,...
995,images/swimming-pool/no/W17D_22_41.tif,3911391,2025-06-12 09:03:38+00:00
996,images/swimming-pool/no/W17D_22_45.tif,4134574,2025-06-12 09:03:38+00:00
997,images/swimming-pool/no/W17D_22_46.tif,4125109,2025-06-12 09:03:38+00:00
998,images/swimming-pool/no/W17D_22_47.tif,4147367,2025-06-12 09:03:38+00:00
999,images/swimming-pool/no/W17D_22_55.tif,4192969,2025-06-12 09:03:38+00:00

In [3]:
import json


print(json.dumps(response, indent=4, default=str))

{
    "ResponseMetadata": {
        "RequestId": "7AH9WZ1G5PMPVEFK",
        "HostId": "WEqdhvabktRAR/tYrtrF50A8f4J31+yTgSQrhp0ZrMPdZci0e47EyA3++cNOBQP5n4Jhm8q9Yk2UQuUCX8HSgx0Wihn889O7",
        "HTTPStatusCode": 200,
        "HTTPHeaders": {
            "x-amz-id-2": "WEqdhvabktRAR/tYrtrF50A8f4J31+yTgSQrhp0ZrMPdZci0e47EyA3++cNOBQP5n4Jhm8q9Yk2UQuUCX8HSgx0Wihn889O7",
            "x-amz-request-id": "7AH9WZ1G5PMPVEFK",
            "date": "Sat, 22 Aug 2026 08:04:34 GMT",
            "x-amz-bucket-region": "af-south-1",
            "content-type": "application/xml",
            "transfer-encoding": "chunked",
            "server": "AmazonS3"
        },
        "RetryAttempts": 0
    },
    "IsTruncated": true,
    "Contents": [
        {
            "Key": "city-hex-polygons-7.geojson",
            "LastModified": "2021-05-14 09:52:18+00:00",
            "ETag": "\"f04048ba5a5ab4aff096a55935bcd447\"",
            "Size": 276231,
            "StorageClass": "STANDARD"
        },
        {
            "Key": "city-hex-polygons-8-10.geojson",
            "LastModified": "2021-05-14 09:44:09+00:00",
            "ETag": "\"1b257eed30f40a4645b4021567fcf0b7-7\"",
            "Size": 108254980,
            "StorageClass": "INTELLIGENT_TIERING"
        },
        {
            "Key": "city-hex-polygons-8.geojson",
            "LastModified": "2021-05-14 13:10:00+00:00",
            "ETag": "\"88f619d038fda0dc7d7260bde74ad9ff\"",
            "Size": 1966685,
            "StorageClass": "STANDARD"
        },
        {
            "Key": "ds_code_challenge_creds.json",
            "LastModified": "2021-05-14 16:34:40+00:00",
            "ETag": "\"930b44cc42b2f82e527414c6f9b43c94\"",
            "Size": 115,
            "StorageClass": "STANDARD"
        },
        {
            "Key": "images/swimming-pool/no/W07C_11_100.tif",
            "LastModified": "2025-06-12 09:03:22+00:00",
            "ETag": "\"fa50c335ad484947a127970abb5d0b9f\"",
            "ChecksumAlgorithm": [
                "CRC64NVME"
            ],
            "ChecksumType": "FULL_OBJECT",
            "Size": 3932696,
            "StorageClass": "STANDARD"
        },
        {
            "Key": "images/swimming-pool/no/W07C_11_61.tif",
            "LastModified": "2025-06-12 09:03:22+00:00",
            "ETag": "\"0b13f4a1a0563e95876bf5c49b994d1d\"",
            "ChecksumAlgorithm": [
                "CRC64NVME"
            ],
            "ChecksumType": "FULL_OBJECT",
            "Size": 3890301,
            "StorageClass": "STANDARD"
        },
        {
            "Key": "images/swimming-pool/no/W07C_11_71.tif",
            "LastModified": "2025-06-12 09:03:22+00:00",
            "ETag": "\"1c9d1faee1517b6c220e821dc87973c2\"",
            "ChecksumAlgorithm": [
                "CRC64NVME"
            ],
            "ChecksumType": "FULL_OBJECT",
            "Size": 3933726,
            "StorageClass": "STANDARD"
        },
        {
            "Key": "images/swimming-pool/no/W07C_11_82.tif",
            "LastModified": "2025-06-12 09:03:22+00:00",
            "ETag": "\"e998a5728b0be00b7ba88fcfbec40078\"",
            "ChecksumAlgorithm": [
                "CRC64NVME"
            ],
            "ChecksumType": "FULL_OBJECT",
            "Size": 4070683,
            "StorageClass": "STANDARD"
        },
        {
            "Key": "images/swimming-pool/no/W07C_11_88.tif",
            "LastModified": "2025-06-12 09:03:22+00:00",
            "ETag": "\"a8df47dc920f427f83f7f101282ad91c\"",
            "ChecksumAlgorithm": [
                "CRC64NVME"
            ],
            "ChecksumType": "FULL_OBJECT",
            "Size": 4006274,
            "StorageClass": "STANDARD"
        },
        {
            "Key": "images/swimming-pool/no/W07C_11_97.tif",
            "LastModified": "2025-06-12 09:03:22+00:00",
            "ETag": "\"fd5e6ca208a601fb56bc680d5b45e3bd\"",
            "ChecksumAlgorithm": [
                "CRC64NVME"
            ],
            "ChecksumType": "FULL_OBJECT",
            "Size": 4412789,
            "StorageClass": "STANDARD"
        },
        {
            "Key": "images/swimming-pool/no/W07C_16_1.tif",
            "LastModified": "2025-06-12 09:03:22+00:00",
            "ETag": "\"a340e4f434dfc6b227003691a844bc88\"",
            "ChecksumAlgorithm": [
                "CRC64NVME"
            ],
            "ChecksumType": "FULL_OBJECT",
            "Size": 3918811,
            "StorageClass": "STANDARD"
        },
        {
            "Key": "images/swimming-pool/no/W07C_16_10.tif",
            "LastModified": "2025-06-12 09:03:22+00:00",
            "ETag": "\"634ff3cf14e8f0a4b3813248db7b7a53\"",
            "ChecksumAlgorithm": [
                "CRC64NVME"
            ],
            "ChecksumType": "FULL_OBJECT",
            "Size": 4344423,
            "StorageClass": "STANDARD"
        },
        {
            "Key": "images/swimming-pool/no/W07C_16_17.tif",
            "LastModified": "2025-06-12 09:03:22+00:00",
            "ETag": "\"7d26d7ef0cf5336e72b1e1117f0416b4\"",
            "ChecksumAlgorithm": [
                "CRC64NVME"
            ],
            "ChecksumType": "FULL_OBJECT",
            "Size": 4053080,
            "StorageClass": "STANDARD"
        },
        {
            "Key": "images/swimming-pool/no/W07C_16_24.tif",
            "LastModified": "2025-06-12 09:03:22+00:00",
            "ETag": "\"36827d82e90df804613c712244f2a21a\"",
            "ChecksumAlgorithm": [
                "CRC64NVME"
            ],
            "ChecksumType": "FULL_OBJECT",
            "Size": 4179993,
            "StorageClass": "STANDARD"
        },
        {
            "Key": "images/swimming-pool/no/W07C_16_25.tif",
            "LastModified": "2025-06-12 09:03:22+00:00",
            "ETag": "\"a8beda0025bc8102a1d7e70b60c7d812\"",
            "ChecksumAlgorithm": [
                "CRC64NVME"
            ],
            "ChecksumType": "FULL_OBJECT",
            "Size": 3891136,
            "StorageClass": "STANDARD"
        },
        {
            "Key": "images/swimming-pool/no/W07C_16_27.tif",
            "LastModified": "2025-06-12 09:03:22+00:00",
            "ETag": "\"2e920a6865a2751b08729b06047e9eaf\"",
            "ChecksumAlgorithm": [
                "CRC64NVME"
            ],
            "ChecksumType": "FULL_OBJECT",
            "Size": 4526008,
            "StorageClass": "STANDARD"
        },
        {
            "Key": "images/swimming-pool/no/W07C_16_29.tif",
            "LastModified": "2025-06-12 09:03:22+00:00",
            "ETag": "\"ff469bed5027237e6ff40e43b27b800f\"",
            "ChecksumAlgorithm": [
                "CRC64NVME"
            ],
            "ChecksumType": "FULL_OBJECT",
            "Size": 4307569,
            "StorageClass": "STANDARD"
        },
        {
            "Key": "images/swimming-pool/no/W07C_16_35.tif",
            "LastModified": "2025-06-12 09:03:22+00:00",
            "ETag": "\"496e62b859b00f3a55b2deb56e8bb9a7\"",
            "ChecksumAlgorithm": [
                "CRC64NVME"
            ],
            "ChecksumType": "FULL_OBJECT",
            "Size": 4143951,
            "StorageClass": "STANDARD"
        },
        {
            "Key": "images/swimming-pool/no/W07C_16_36.tif",
            "LastModified": "2025-06-12 09:03:22+00:00",
            "ETag": "\"0102ca3e8a2ff51c0519cf7055bcc5bb\"",
            "ChecksumAlgorithm": [
                "CRC64NVME"
            ],
            "ChecksumType": "FULL_OBJECT",
            "Size": 4142070,
            "StorageClass": "STANDARD"
        },
        {
            "Key": "images/swimming-pool/no/W07C_16_38.tif",
            "LastModified": "2025-06-12 09:03:22+00:00",
            "ETag": "\"d92e5c87f24288d5e66926f1e4dd7d6a\"",
            "ChecksumAlgorithm": [
                "CRC64NVME"
            ],
            "ChecksumType": "FULL_OBJECT",
            "Size": 4538185,
            "StorageClass": "STANDARD"
        },
        {
            "Key": "images/swimming-pool/no/W07C_16_39.tif",
            "LastModified": "2025-06-12 09:03:22+00:00",
            "ETag": "\"fad8e45d690b488ce353561e9516d6b2\"",
            "ChecksumAlgorithm": [
                "CRC64NVME"
            ],
            "ChecksumType": "FULL_OBJECT",
            "Size": 4203826,
            "StorageClass": "STANDARD"
        },
        {
            "Key": "images/swimming-pool/no/W07C_16_40.tif",
            "LastModified": "2025-06-12 09:03:22+00:00",
            "ETag": "\"c903d406beb54cf5ff270b317e5e53bb\"",
            "ChecksumAlgorithm": [
                "CRC64NVME"
            ],
            "ChecksumType": "FULL_OBJECT",
            "Size": 4284265,
            "StorageClass": "STANDARD"
        },
        {
            "Key": "images/swimming-pool/no/W07C_16_45.tif",
            "LastModified": "2025-06-12 09:03:22+00:00",
            "ETag": "\"edc3c3f418334053312fbd7374776871\"",
            "ChecksumAlgorithm": [
                "CRC64NVME"
            ],
            "ChecksumType": "FULL_OBJECT",
            "Size": 4411267,
            "StorageClass": "STANDARD"
        },
        {
            "Key": "images/swimming-pool/no/W07C_16_46.tif",
            "LastModified": "2025-06-12 09:03:22+00:00",
            "ETag": "\"fba269508a5eabe37b2e017f00253687\"",
            "ChecksumAlgorithm": [
                "CRC64NVME"
            ],
            "ChecksumType": "FULL_OBJECT",
            "Size": 4293089,
            "StorageClass": "STANDARD"
        },
        {
            "Key": "images/swimming-pool/no/W07C_16_47.tif",
            "LastModified": "2025-06-12 09:03:22+00:00",
            "ETag": "\"bec9185239689991a168fcd897a07997\"",
            "ChecksumAlgorithm": [
                "CRC64NVME"
            ],
            "ChecksumType": "FULL_OBJECT",
            "Size": 4271324,
            "StorageClass": "STANDARD"
        },
        {
            "Key": "images/swimming-pool/no/W07C_16_5.tif",
            "LastModified": "2025-06-12 09:03:22+00:00",
            "ETag": "\"bc06bb6cea589eaceec92639a53e0410\"",
            "ChecksumAlgorithm": [
                "CRC64NVME"
            ],
            "ChecksumType": "FULL_OBJECT",
            "Size": 4300757,
            "StorageClass": "STANDARD"
        },
        {
            "Key": "images/swimming-pool/no/W07C_16_52.tif",
            "LastModified": "2025-06-12 09:03:22+00:00",
            "ETag": "\"5a4c28040b8918797fdad4a605ac1e41\"",
            "ChecksumAlgorithm": [
                "CRC64NVME"
            ],
            "ChecksumType": "FULL_OBJECT",
            "Size": 4314228,
            "StorageClass": "STANDARD"
        },
        {
            "Key": "images/swimming-pool/no/W07C_16_53.tif",
            "LastModified": "2025-06-12 09:03:22+00:00",
            "ETag": "\"859a2cb970049eae55ca3df881d249a4\"",
            "ChecksumAlgorithm": [
                "CRC64NVME"
            ],
            "ChecksumType": "FULL_OBJECT",
            "Size": 4406915,
            "StorageClass": "STANDARD"
        },
        {
            "Key": "images/swimming-pool/no/W07C_16_6.tif",
            "LastModified": "2025-06-12 09:03:22+00:00",
            "ETag": "\"a5732adb46bcaa1e427461a0574b641c\"",
            "ChecksumAlgorithm": [
                "CRC64NVME"
            ],
            "ChecksumType": "FULL_OBJECT",
            "Size": 4121799,
            "StorageClass": "STANDARD"
        },
        {
            "Key": "images/swimming-pool/no/W07C_16_62.tif",
            "LastModified": "2025-06-12 09:03:22+00:00",
            "ETag": "\"20b7dcd9f438596e652620b6066b237a\"",
            "ChecksumAlgorithm": [
                "CRC64NVME"
            ],
            "ChecksumType": "FULL_OBJECT",
            "Size": 4467450,
            "StorageClass": "STANDARD"
        },
        {
            "Key": "images/swimming-pool/no/W07C_16_64.tif",
            "LastModified": "2025-06-12 09:03:22+00:00",
            "ETag": "\"51170c36a458b449415bb563da8c9848\"",
            "ChecksumAlgorithm": [
                "CRC64NVME"
            ],
            "ChecksumType": "FULL_OBJECT",
            "Size": 4409861,
            "StorageClass": "STANDARD"
        },
        {
            "Key": "images/swimming-pool/no/W07C_16_67.tif",
            "LastModified": "2025-06-12 09:03:22+00:00",
            "ETag": "\"c5e083577ef9a0ef91ed222376705dc1\"",
            "ChecksumAlgorithm": [
                "CRC64NVME"
            ],
            "ChecksumType": "FULL_OBJECT",
            "Size": 4369768,
            "StorageClass": "STANDARD"
        },
        {
            "Key": "images/swimming-pool/no/W07C_16_68.tif",
            "LastModified": "2025-06-12 09:03:22+00:00",
            "ETag": "\"d1a3c4cb132905e56e0ec87c3264995d\"",
            "ChecksumAlgorithm": [
                "CRC64NVME"
            ],
            "ChecksumType": "FULL_OBJECT",
            "Size": 4272824,
            "StorageClass": "STANDARD"
        },
        {
            "Key": "images/swimming-pool/no/W07C_16_78.tif",
            "LastModified": "2025-06-12 09:03:22+00:00",
            "ETag": "\"16d42792a5efed25a760aafcba512b70\"",
            "ChecksumAlgorithm": [
                "CRC64NVME"
            ],
            "ChecksumType": "FULL_OBJECT",
            "Size": 4112080,
            "StorageClass": "STANDARD"
        },
        {
            "Key": "images/swimming-pool/no/W07C_16_82.tif",
            "LastModified": "2025-06-12 09:03:22+00:00",
            "ETag": "\"7dc17d38740ad3fd3ab4ef65fbd578f7\"",
            "ChecksumAlgorithm": [
                "CRC64NVME"
            ],
            "ChecksumType": "FULL_OBJECT",
            "Size": 4048325,
            "StorageClass": "STANDARD"
        },
        {
            "Key": "images/swimming-pool/no/W07C_16_83.tif",
            "LastModified": "2025-06-12 09:03:23+00:00",
            "ETag": "\"658d083b3661e480fbb4df643374f92a\"",
            "ChecksumAlgorithm": [
                "CRC64NVME"
            ],
            "ChecksumType": "FULL_OBJECT",
            "Size": 3681123,
            "StorageClass": "STANDARD"
        },
        {
            "Key": "images/swimming-pool/no/W07C_16_84.tif",
            "LastModified": "2025-06-12 09:03:23+00:00",
            "ETag": "\"e6e874fcb625ea97febc1b986f33b55c\"",
            "ChecksumAlgorithm": [
                "CRC64NVME"
            ],
            "ChecksumType": "FULL_OBJECT",
            "Size": 3727188,
            "StorageClass": "STANDARD"
        },
        {
            "Key": "images/swimming-pool/no/W07C_16_86.tif",
            "LastModified": "2025-06-12 09:03:23+00:00",
            "ETag": "\"68c396dcae146aa845de78073aedaaee\"",
            "ChecksumAlgorithm": [
                "CRC64NVME"
            ],
            "ChecksumType": "FULL_OBJECT",
            "Size": 4515546,
            "StorageClass": "STANDARD"
        },
        {
            "Key": "images/swimming-pool/no/W07C_16_88.tif",
            "LastModified": "2025-06-12 09:03:23+00:00",
            "ETag": "\"efe9e442ff15d4300b28f4a31fe264ed\"",
            "ChecksumAlgorithm": [
                "CRC64NVME"
            ],
            "ChecksumType": "FULL_OBJECT",
            "Size": 3442853,
            "StorageClass": "STANDARD"
        },
        {
            "Key": "images/swimming-pool/no/W07C_16_93.tif",
            "LastModified": "2025-06-12 09:03:23+00:00",
            "ETag": "\"a4459982a1e8c579be88e5fb52f9282a\"",
            "ChecksumAlgorithm": [
                "CRC64NVME"
            ],
            "ChecksumType": "FULL_OBJECT",
            "Size": 3583078,
            "StorageClass": "STANDARD"
        },
        {
            "Key": "images/swimming-pool/no/W07C_16_96.tif",
            "LastModified": "2025-06-12 09:03:23+00:00",
            "ETag": "\"5f53050758c72a73bf18f7e03bd49ae0\"",
            "ChecksumAlgorithm": [
                "CRC64NVME"
            ],
            "ChecksumType": "FULL_OBJECT",
            "Size": 4225642,
            "StorageClass": "STANDARD"
        },
        {
            "Key": "images/swimming-pool/no/W07C_16_97.tif",
            "LastModified": "2025-06-12 09:03:23+00:00",
            "ETag": "\"9cfefd19ed6e188be3cbb6f12fb8fa1b\"",
            "ChecksumAlgorithm": [
                "CRC64NVME"
            ],
            "ChecksumType": "FULL_OBJECT",
            "Size": 4059253,
            "StorageClass": "STANDARD"
        },
        {
            "Key": "images/swimming-pool/no/W07C_17_13.tif",
            "LastModified": "2025-06-12 09:03:23+00:00",
            "ETag": "\"e17002a95e20309d4f8a8edbeff514bf\"",
            "ChecksumAlgorithm": [
                "CRC64NVME"
            ],
            "ChecksumType": "FULL_OBJECT",
            "Size": 4275177,
            "StorageClass": "STANDARD"
        },
        {
            "Key": "images/swimming-pool/no/W07C_17_21.tif",
            "LastModified": "2025-06-12 09:03:23+00:00",
            "ETag": "\"e5ab58c2e4d659f2dfb47b54fa8a782f\"",
            "ChecksumAlgorithm": [
                "CRC64NVME"
            ],
            "ChecksumType": "FULL_OBJECT",
            "Size": 4356655,
            "StorageClass": "STANDARD"
        },
        {
            "Key": "images/swimming-pool/no/W07C_17_31.tif",
            "LastModified": "2025-06-12 09:03:23+00:00",
            "ETag": "\"f0de970fe783236e6f258eb6008f4e9a\"",
            "ChecksumAlgorithm": [
                "CRC64NVME"
            ],
            "ChecksumType": "FULL_OBJECT",
            "Size": 4292477,
            "StorageClass": "STANDARD"
        },
        {
            "Key": "images/swimming-pool/no/W07C_21_13.tif",
            "LastModified": "2025-06-12 09:03:23+00:00",
            "ETag": "\"2eef42d9ee9563cadbbcaec120d9bf7b\"",
            "ChecksumAlgorithm": [
                "CRC64NVME"
            ],
            "ChecksumType": "FULL_OBJECT",
            "Size": 3980342,
            "StorageClass": "STANDARD"
        },
        {
            "Key": "images/swimming-pool/no/W07C_21_17.tif",
            "LastModified": "2025-06-12 09:03:23+00:00",
            "ETag": "\"7389a5093f10e346034dda7282cd7215\"",
            "ChecksumAlgorithm": [
                "CRC64NVME"
            ],
            "ChecksumType": "FULL_OBJECT",
            "Size": 4436123,
            "StorageClass": "STANDARD"
        },
        {
            "Key": "images/swimming-pool/no/W07C_21_22.tif",
            "LastModified": "2025-06-12 09:03:23+00:00",
            "ETag": "\"f34ad58beb21a7a7c28b92b972bd651d\"",
            "ChecksumAlgorithm": [
                "CRC64NVME"
            ],
            "ChecksumType": "FULL_OBJECT",
            "Size": 4151340,
            "StorageClass": "STANDARD"
        },
        {
            "Key": "images/swimming-pool/no/W07C_21_23.tif",
            "LastModified": "2025-06-12 09:03:23+00:00",
            "ETag": "\"53252b0adfed307fea4c323761eabfc4\"",
            "ChecksumAlgorithm": [
                "CRC64NVME"
            ],
            "ChecksumType": "FULL_OBJECT",
            "Size": 3870081,
            "StorageClass": "STANDARD"
        },
        {
            "Key": "images/swimming-pool/no/W07C_21_26.tif",
            "LastModified": "2025-06-12 09:03:23+00:00",
            "ETag": "\"88d876f19c237e7487379f1c494d2b5e\"",
            "ChecksumAlgorithm": [
                "CRC64NVME"
            ],
            "ChecksumType": "FULL_OBJECT",
            "Size": 4198648,
            "StorageClass": "STANDARD"
        },
        {
            "Key": "images/swimming-pool/no/W07C_21_42.tif",
            "LastModified": "2025-06-12 09:03:23+00:00",
            "ETag": "\"b31bf007a190634f903c6c2c7e9da54d\"",
            "ChecksumAlgorithm": [
                "CRC64NVME"
            ],
            "ChecksumType": "FULL_OBJECT",
            "Size": 4237432,
            "StorageClass": "STANDARD"

In [13]:
files_df["file_type"] = (
    files_df["key"]
    .str.lower()
    .str.split(".")
    .str[-1]
)

files_df["file_type"].value_counts()

file_type
tif        996
geojson      3
json         1
Name: count, dtype: int64

In [15]:
import json

KEY = "city-hex-polygons-7.geojson"

response = s3.get_object(
    Bucket=BUCKET,
    Key=KEY
)

geojson_data = json.loads(
    response["Body"].read()
)

type(geojson_data)

dict

In [16]:
geojson_data.keys()

dict_keys(['type', 'name', 'crs', 'features'])

In [17]:
len(geojson_data["features"])

627

In [18]:
geojson_data["features"][0]

{'type': 'Feature',
 'properties': {'index': '87ad36180ffffff'},
 'geometry': {'type': 'Polygon',
  'coordinates': [[[18.69026825870867, -33.86703319751351],
    [18.69168980931549, -33.85511764511594],
    [18.679265404549795, -33.84751122474886],
    [18.66542004486691, -33.8518201940735],
    [18.663997091762614, -33.86373510896562],
    [18.676420900551488, -33.87134169227918],
    [18.69026825870867, -33.86703319751351]]]}}

In [19]:
features_df = pd.json_normalize(
    geojson_data["features"]
)

features_df.head()

,type,properties.index,geometry.type,geometry.coordinates
0,Feature,87ad36180ffffff,Polygon,"[[[18.69026825870867, -33.86703319751351], [18..."
1,Feature,87ad36181ffffff,Polygon,"[[[18.663997091762614, -33.86373510896562], [1..."
2,Feature,87ad36182ffffff,Polygon,"[[[18.705536812042357, -33.850805737933875], [..."
3,Feature,87ad36183ffffff,Polygon,"[[[18.679265404549795, -33.84751122474886], [1..."
4,Feature,87ad36184ffffff,Polygon,"[[[18.70127401694917, -33.88655041755364], [18..."

In [20]:
# Number of rows and columns
features_df.shape

(627, 4)

In [21]:
features_df.dtypes

type                    object
properties.index        object
geometry.type           object
geometry.coordinates    object
dtype: object

In [22]:
# Check whether the hex IDs are unique
features_df["properties.index"].nunique()

627

discovery finding:

Source: city-hex-polygons-7.geojson
Format: GeoJSON
Records: 627
Geometry: Polygon
Business/geospatial identifier: properties.index
Unique identifiers: 627 / 627

In [23]:
features_df.isnull().sum()

type                    0
properties.index        0
geometry.type           0
geometry.coordinates    0
dtype: int64

In [24]:
features_df["geometry.type"].value_counts()

geometry.type
Polygon    627
Name: count, dtype: int64

In [25]:
features_df["type"].value_counts()

type
Feature    627
Name: count, dtype: int64

what axctly is in the the 1,000 objects

In [26]:
files_df["file_type"].value_counts()

file_type
tif        996
geojson      3
json         1
Name: count, dtype: int64

In [27]:
files_df[
    files_df["key"].str.startswith("images/")
]["key"].head(20)

4     images/swimming-pool/no/W07C_11_100.tif
5      images/swimming-pool/no/W07C_11_61.tif
6      images/swimming-pool/no/W07C_11_71.tif
7      images/swimming-pool/no/W07C_11_82.tif
8      images/swimming-pool/no/W07C_11_88.tif
9      images/swimming-pool/no/W07C_11_97.tif
10      images/swimming-pool/no/W07C_16_1.tif
11     images/swimming-pool/no/W07C_16_10.tif
12     images/swimming-pool/no/W07C_16_17.tif
13     images/swimming-pool/no/W07C_16_24.tif
14     images/swimming-pool/no/W07C_16_25.tif
15     images/swimming-pool/no/W07C_16_27.tif
16     images/swimming-pool/no/W07C_16_29.tif
17     images/swimming-pool/no/W07C_16_35.tif
18     images/swimming-pool/no/W07C_16_36.tif
19     images/swimming-pool/no/W07C_16_38.tif
20     images/swimming-pool/no/W07C_16_39.tif
21     images/swimming-pool/no/W07C_16_40.tif
22     images/swimming-pool/no/W07C_16_45.tif
23     images/swimming-pool/no/W07C_16_46.tif
Name: key, dtype: object

In [29]:
service_request_files = files_df[
    files_df["key"].str.contains(
        r"(^|/)(sr|sr_hex|sr_hex_truncated)",
        case=False,
        regex=True
    )
]

service_request_files

C:\Users\User\AppData\Local\Temp\ipykernel_17352\290442126.py:2: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  files_df["key"].str.contains(

Empty DataFrame
Columns: [key, size_bytes, last_modified, file_type]
Index: []

In [30]:
print(f"Total S3 objects discovered: {len(files_df):,}")

Total S3 objects discovered: 1,000

In [32]:
geojson_files = files_df[
    files_df["key"].str.contains(
        "city-hex",
        case=False,
        na=False
    )
]

geojson_files

,key,size_bytes,last_modified,file_type
0,city-hex-polygons-7.geojson,276231,2021-05-14 09:52:18+00:00,geojson
1,city-hex-polygons-8-10.geojson,108254980,2021-05-14 09:44:09+00:00,geojson
2,city-hex-polygons-8.geojson,1966685,2021-05-14 13:10:00+00:00,geojson

In [33]:
required_sources = [
    "sr.csv.gz",
    "sr_hex.csv.gz",
    "sr_hex_truncated.csv",
    "city-hex-polygons-8.geojson",
    "city-hex-polygons-8-10.geojson",
]

source_check = []

for key in required_sources:
    try:
        response = s3.head_object(
            Bucket=BUCKET,
            Key=key
        )

        source_check.append({
            "key": key,
            "exists": True,
            "size_bytes": response["ContentLength"],
            "last_modified": response["LastModified"],
        })

    except s3.exceptions.ClientError as exc:
        source_check.append({
            "key": key,
            "exists": False,
            "size_bytes": None,
            "last_modified": None,
            "error": exc.response["Error"]["Code"],
        })

source_check_df = pd.DataFrame(source_check)

source_check_df

,key,exists,size_bytes,last_modified
0,sr.csv.gz,True,37183035,2022-06-21 20:13:07+00:00
1,sr_hex.csv.gz,True,36657416,2022-06-21 20:13:19+00:00
2,sr_hex_truncated.csv,True,63403673,2022-06-21 20:13:32+00:00
3,city-hex-polygons-8.geojson,True,1966685,2021-05-14 13:10:00+00:00
4,city-hex-polygons-8-10.geojson,True,108254980,2021-05-14 09:44:09+00:00

one we have pictur of our sources in the s3 bucket as specified

In [34]:
required_sources = [
    "city-hex-polygons-8-10.geojson",
    "city-hex-polygons-8.geojson",
    "sr.csv.gz",
    "sr_hex.csv.gz",
    "sr_hex_truncated.csv",
]

source_inventory = files_df[
    files_df["key"].isin(required_sources)
].copy()

source_inventory

,key,size_bytes,last_modified,file_type
1,city-hex-polygons-8-10.geojson,108254980,2021-05-14 09:44:09+00:00,geojson
2,city-hex-polygons-8.geojson,1966685,2021-05-14 13:10:00+00:00,geojson

get all the object in the storage

In [35]:
required_sources = [
    "city-hex-polygons-8-10.geojson",
    "city-hex-polygons-8.geojson",
    "sr.csv.gz",
    "sr_hex.csv.gz",
    "sr_hex_truncated.csv",
]

source_inventory = []

for key in required_sources:
    response = s3.head_object(
        Bucket=BUCKET,
        Key=key
    )

    source_inventory.append({
        "key": key,
        "size_bytes": response["ContentLength"],
        "last_modified": response["LastModified"],
    })

source_inventory_df = pd.DataFrame(source_inventory)

source_inventory_df

                              key  size_bytes             last_modified
0  city-hex-polygons-8-10.geojson   108254980 2021-05-14 09:44:09+00:00
1     city-hex-polygons-8.geojson     1966685 2021-05-14 13:10:00+00:00
2                       sr.csv.gz    37183035 2022-06-21 20:13:07+00:00
3                   sr_hex.csv.gz    36657416 2022-06-21 20:13:19+00:00
4            sr_hex_truncated.csv    63403673 2022-06-21 20:13:32+00:00

In [37]:
%pip install s3fs

Collecting s3fs
  Downloading s3fs-2026.7.0-py3-none-any.whl (32 kB)
Collecting aiohttp!=4.0.0a0,!=4.0.0a1,>=3.9.0
  Downloading aiohttp-3.14.3-cp310-cp310-win_amd64.whl (480 kB)
Collecting fsspec<2026.7.1,>=2026.7.0
  Downloading fsspec-2026.7.0-py3-none-any.whl (206 kB)
Collecting aiobotocore<4.0.0,>=2.19.0
  Downloading aiobotocore-3.9.0-py3-none-any.whl (100 kB)
Collecting aioitertools<1.0.0,>=0.5.1
  Downloading aioitertools-0.13.0-py3-none-any.whl (24 kB)
Collecting wrapt<3.0.0,>=1.10.10
  Downloading wrapt-2.3.0-cp310-cp310-win_amd64.whl (80 kB)
Requirement already satisfied: typing-extensions<5.0.0,>=4.14.0 in c:\programdata\anaconda3\envs\pythonproject\lib\site-packages (from aiobotocore<4.0.0,>=2.19.0->s3fs) (4.16.0)
Collecting multidict<7.0.0,>=6.0.0
  Downloading multidict-6.7.1-cp310-cp310-win_amd64.whl (46 kB)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in c:\programdata\anaconda3\envs\pythonproject\lib\site-packages (from aiobotocore<4.0.0,>=2.19.0->s3fs) (1.1.0)
Collecting botocore<1.43.57,>=1.43.3
  Downloading botocore-1.43.56-py3-none-any.whl (15.4 MB)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in c:\programdata\anaconda3\envs\pythonproject\lib\site-packages (from aiobotocore<4.0.0,>=2.19.0->s3fs) (2.9.0.post0)
Collecting frozenlist>=1.1.1
  Downloading frozenlist-1.8.0-cp310-cp310-win_amd64.whl (43 kB)
Collecting aiohappyeyeballs>=2.5.0
  Downloading aiohappyeyeballs-2.7.1-py3-none-any.whl (15 kB)
Collecting propcache>=0.2.0
  Downloading propcache-0.5.2-cp310-cp310-win_amd64.whl (42 kB)
Collecting yarl<2.0,>=1.17.0
  Downloading yarl-1.24.5-cp310-cp310-win_amd64.whl (97 kB)
Collecting attrs>=17.3.0
  Downloading attrs-26.1.0-py3-none-any.whl (67 kB)
Collecting aiosignal>=1.4.0
  Downloading aiosignal-1.4.0-py3-none-any.whl (7.5 kB)
Collecting async-timeout<6.0,>=4.0
  Using cached async_timeout-5.0.1-py3-none-any.whl (6.2 kB)
Requirement already satisfied: urllib3!=2.2.0,<3,>=1.25.4 in c:\programdata\anaconda3\envs\pythonproject\lib\site-packages (from botocore<1.43.57,>=1.43.3->aiobotocore<4.0.0,>=2.19.0->s3fs) (2.7.0)
Requirement already satisfied: six>=1.5 in c:\programdata\anaconda3\envs\pythonproject\lib\site-packages (from python-dateutil<3.0.0,>=2.1->aiobotocore<4.0.0,>=2.19.0->s3fs) (1.17.0)
Collecting idna>=2.0
  Downloading idna-3.19-py3-none-any.whl (68 kB)
Installing collected packages: propcache, multidict, idna, frozenlist, yarl, attrs, async-timeout, aiosignal, aiohappyeyeballs, wrapt, botocore, aioitertools, aiohttp, fsspec, aiobotocore, s3fs
  Attempting uninstall: botocore
    Found existing installation: botocore 1.43.77
    Uninstalling botocore-1.43.77:
      Successfully uninstalled botocore-1.43.77
Successfully installed aiobotocore-3.9.0 aiohappyeyeballs-2.7.1 aiohttp-3.14.3 aioitertools-0.13.0 aiosignal-1.4.0 async-timeout-5.0.1 attrs-26.1.0 botocore-1.43.56 frozenlist-1.8.0 fsspec-2026.7.0 idna-3.19 multidict-6.7.1 propcache-0.5.2 s3fs-2026.7.0 wrapt-2.3.0 yarl-1.24.5
Note: you may need to restart the kernel to use updated packages.

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
boto3 1.43.77 requires botocore<1.44.0,>=1.43.77, but you have botocore 1.43.56 which is incompatible.

In [38]:
import pandas as pd

sr = pd.read_csv(
    f"s3://{BUCKET}/sr.csv.gz",
    compression="gzip"
)

print(f"Rows: {len(sr):,}")
print(f"Columns: {len(sr.columns):,}")

Rows: 941,634
Columns: 16

In [39]:
sr.columns.tolist()

['Unnamed: 0',
 'notification_number',
 'reference_number',
 'creation_timestamp',
 'completion_timestamp',
 'directorate',
 'department',
 'branch',
 'section',
 'code_group',
 'code',
 'cause_code_group',
 'cause_code',
 'official_suburb',
 'latitude',
 'longitude']

In [40]:
sr.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 941634 entries, 0 to 941633
Data columns (total 16 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Unnamed: 0            941634 non-null  int64
 1   notification_number   941634 non-null  int64
 2   reference_number      592920 non-null  float64
 3   creation_timestamp    941634 non-null  object
 4   completion_timestamp  929442 non-null  object
 5   directorate           932199 non-null  object
 6   department            932180 non-null  object
 7   branch                913233 non-null  object
 8   section               848509 non-null  object
 9   code_group            941634 non-null  object
 10  code                  941634 non-null  object
 11  cause_code_group      131117 non-null  object
 12  cause_code            129669 non-null  object
 13  official_suburb       729221 non-null  object
 14  latitude              729270 non-null  float64
 15  longitude             729270 non-null  float64
dtypes: float64(3), int64(2), object(11)
memory usage: 114.9+ MB

In [41]:
sr.head()

,Unnamed: 0,notification_number,reference_number,creation_timestamp,completion_timestamp,directorate,department,branch,section,code_group,code,cause_code_group,cause_code,official_suburb,latitude,longitude
0,0,400583534,9.109492e+09,2020-10-07 06:55:18+02:00,2020-10-08 15:36:35+02:00,URBAN MOBILITY,Roads Infrastructure Management,RIM Area Central,District: Blaauwberg,TD Customer complaint groups,Pothole&Defect Road Foot Bic Way/Kerbs,Road (RCL),Wear and tear,MONTAGUE GARDENS,-33.872839,18.522488
1,1,400555043,9.108995e+09,2020-07-09 16:08:13+02:00,2020-07-14 14:27:01+02:00,URBAN MOBILITY,Roads Infrastructure Management,RIM Area East,District : Somerset West,TD Customer complaint groups,Manhole Cover/Gully Grid,Road (RCL),Vandalism,SOMERSET WEST,-34.078916,18.848940
2,2,400589145,9.109614e+09,2020-10-27 10:21:59+02:00,2020-10-28 17:48:15+02:00,URBAN MOBILITY,Roads Infrastructure Management,RIM Area East,District : Somerset West,TD Customer complaint groups,Manhole Cover/Gully Grid,Road (RCL),Vandalism,STRAND,-34.102242,18.821116
3,3,400538915,9.108601e+09,2020-03-19 06:36:06+02:00,2021-03-29 20:34:19+02:00,URBAN MOBILITY,Roads Infrastructure Management,RIM Area North,District : Bellville,TD Customer complaint groups,Paint Markings Lines&Signs,Road Markings,Wear and tear,RAVENSMEAD,-33.920019,18.607209
4,4,400568554,NaN,2020-08-25 09:48:42+02:00,2020-08-31 08:41:13+02:00,URBAN MOBILITY,Roads Infrastructure Management,RIM Area South,District : Athlone,TD Customer complaint groups,Pothole&Defect Road Foot Bic Way/Kerbs,Road (RCL),Surfacing failure,CLAREMONT,-33.987400,18.453760

In [45]:
sr[["latitude", "longitude"]].isna().sum()

latitude     212364
longitude    212364
dtype: int64

In [46]:
coordinate_nulls = sr[["latitude", "longitude"]].isna().sum()

coordinate_nulls

latitude     212364
longitude    212364
dtype: int64

In [47]:
print("Total records:", len(sr))
print("Records with coordinates:", sr[["latitude", "longitude"]].notna().all(axis=1).sum())
print("Records missing coordinates:", sr[["latitude", "longitude"]].isna().any(axis=1).sum())
print("Coordinate completeness:", f"{sr[['latitude', 'longitude']].notna().all(axis=1).mean():.2%}")

Total records: 941634
Records with coordinates: 729270
Records missing coordinates: 212364
Coordinate completeness: 77.45%

Load sr_hex.csv.gz

In [48]:
sr_hex =pd.read_csv(f"s3://{BUCKET}/sr_hex.csv.gz", compression="gzip")

In [49]:
print("Rows:", len(sr_hex))
print("Columns:", len(sr_hex.columns))

Rows: 941634
Columns: 16

In [56]:
sr_hex.columns.tolist()

['notification_number',
 'reference_number',
 'creation_timestamp',
 'completion_timestamp',
 'directorate',
 'department',
 'branch',
 'section',
 'code_group',
 'code',
 'cause_code_group',
 'cause_code',
 'official_suburb',
 'latitude',
 'longitude',
 'h3_level8_index']

In [57]:
sr_hex.head(10)

,notification_number,reference_number,creation_timestamp,completion_timestamp,directorate,department,branch,section,code_group,code,cause_code_group,cause_code,official_suburb,latitude,longitude,h3_level8_index
0,400583534,9.109492e+09,2020-10-07 06:55:18+02:00,2020-10-08 15:36:35+02:00,URBAN MOBILITY,Roads Infrastructure Management,RIM Area Central,District: Blaauwberg,TD Customer complaint groups,Pothole&Defect Road Foot Bic Way/Kerbs,Road (RCL),Wear and tear,MONTAGUE GARDENS,-33.872839,18.522488,88ad360225fffff
1,400555043,9.108995e+09,2020-07-09 16:08:13+02:00,2020-07-14 14:27:01+02:00,URBAN MOBILITY,Roads Infrastructure Management,RIM Area East,District : Somerset West,TD Customer complaint groups,Manhole Cover/Gully Grid,Road (RCL),Vandalism,SOMERSET WEST,-34.078916,18.848940,88ad36d5e1fffff
2,400589145,9.109614e+09,2020-10-27 10:21:59+02:00,2020-10-28 17:48:15+02:00,URBAN MOBILITY,Roads Infrastructure Management,RIM Area East,District : Somerset West,TD Customer complaint groups,Manhole Cover/Gully Grid,Road (RCL),Vandalism,STRAND,-34.102242,18.821116,88ad36d437fffff
3,400538915,9.108601e+09,2020-03-19 06:36:06+02:00,2021-03-29 20:34:19+02:00,URBAN MOBILITY,Roads Infrastructure Management,RIM Area North,District : Bellville,TD Customer complaint groups,Paint Markings Lines&Signs,Road Markings,Wear and tear,RAVENSMEAD,-33.920019,18.607209,88ad361133fffff
4,400568554,NaN,2020-08-25 09:48:42+02:00,2020-08-31 08:41:13+02:00,URBAN MOBILITY,Roads Infrastructure Management,RIM Area South,District : Athlone,TD Customer complaint groups,Pothole&Defect Road Foot Bic Way/Kerbs,Road (RCL),Surfacing failure,CLAREMONT,-33.987400,18.453760,88ad361709fffff
5,400556029,9.109003e+09,2020-07-11 10:34:37+02:00,2020-07-21 12:35:53+02:00,URBAN MOBILITY,Roads Infrastructure Management,RIM Area East,District : Somerset West,TD Customer complaint groups,Pothole&Defect Road Foot Bic Way/Kerbs,Road (RCL),Base failure,STRAND,-34.119520,18.829917,88ad36d43dfffff
6,400588369,NaN,2020-10-23 10:33:48+02:00,2020-10-26 14:16:49+02:00,URBAN MOBILITY,Roads Infrastructure Management,RIM Area North,District : Bellville,TD Customer complaint groups,Pothole&Defect Road Foot Bic Way/Kerbs,NaN,NaN,GLENHAVEN,-33.917996,18.658031,88ad361a19fffff
7,400549080,NaN,2020-06-17 15:46:11+02:00,2020-11-24 14:26:09+02:00,URBAN MOBILITY,Roads Infrastructure Management,RIM Area North,District : Bellville,TD Customer complaint groups,Pothole&Defect Road Foot Bic Way/Kerbs,NaN,NaN,RAVENSMEAD,-33.922154,18.596821,88ad3611edfffff
8,400599701,9.109845e+09,2020-12-04 08:30:50+02:00,2020-12-14 12:53:52+02:00,URBAN MOBILITY,Roads Infrastructure Management,RIM Area Central,District: Cape Town,TD Customer complaint groups,Block Pipe/Chan/Canal/Drain/Gully/Manh,NaN,NaN,CAPE TOWN CITY CENTRE,-33.925721,18.421675,88ad361519fffff
9,400569986,NaN,2020-08-28 13:37:53+02:00,2020-08-28 16:17:35+02:00,URBAN MOBILITY,Roads Infrastructure Management,RIM Area North,District : Kraaifontein,TD Customer complaint groups,Pothole&Defect Road Foot Bic Way/Kerbs,Road (RCL),Surfacing failure,DURBANVILLE,-33.835098,18.652708,88ad3618e5fffff

In [58]:
coordinate_nulls = sr_hex[["latitude", "longitude"]].isna().sum()

In [59]:
coordinate_nulls

latitude     212364
longitude    212364
dtype: int64

Compare row counts

In [51]:
set(sr_hex.columns) - set(sr.columns)

{'h3_level8_index'}

In [52]:
print("sr rows:", len(sr))
print("sr_hex rows:", len(sr_hex))

sr rows: 941634
sr_hex rows: 941634

In [53]:
sr_hex["h3_level8_index"].value_counts(dropna=False).head()

h3_level8_index
0                  212364
88ad3612a9fffff      3815
88ad361009fffff      3464
88ad368985fffff      3393
88ad361519fffff      2797
Name: count, dtype: int64

In [60]:
print(
    "H3 index 0:",
    (sr_hex["h3_level8_index"] == 0).sum()
)

H3 index 0: 0

In [61]:
print(
    "H3 index 0:",
    (sr_hex["h3_level8_index"] == "0").sum()
)

H3 index 0: 212364

In [62]:
print("Total records:", len(sr_hex))
print("H3 index 0:", (sr_hex["h3_level8_index"] == "0").sum())
print("Valid H3 index:", (sr_hex["h3_level8_index"] != "0").sum())

Total records: 941634
H3 index 0: 212364
Valid H3 index: 729270

GeoJSON reference file.

In [63]:
%pip install geopandas

Collecting geopandas
  Downloading geopandas-1.1.4-py3-none-any.whl (343 kB)
Collecting pyproj>=3.5.0
  Downloading pyproj-3.7.1-cp310-cp310-win_amd64.whl (6.3 MB)
Requirement already satisfied: numpy>=1.24 in c:\programdata\anaconda3\envs\pythonproject\lib\site-packages (from geopandas) (2.2.6)
Collecting shapely>=2.0.0
  Downloading shapely-2.1.2-cp310-cp310-win_amd64.whl (1.7 MB)
Collecting pyogrio>=0.7.2
  Downloading pyogrio-0.13.0-cp310-cp310-win_amd64.whl (23.9 MB)
Requirement already satisfied: packaging in c:\programdata\anaconda3\envs\pythonproject\lib\site-packages (from geopandas) (26.3)
Requirement already satisfied: pandas>=2.0.0 in c:\programdata\anaconda3\envs\pythonproject\lib\site-packages (from geopandas) (2.3.3)
Requirement already satisfied: tzdata>=2022.7 in c:\programdata\anaconda3\envs\pythonproject\lib\site-packages (from pandas>=2.0.0->geopandas) (2026.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\programdata\anaconda3\envs\pythonproject\lib\site-packages (from pandas>=2.0.0->geopandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\programdata\anaconda3\envs\pythonproject\lib\site-packages (from pandas>=2.0.0->geopandas) (2026.3.post1)
Requirement already satisfied: certifi in c:\programdata\anaconda3\envs\pythonproject\lib\site-packages (from pyogrio>=0.7.2->geopandas) (2026.7.22)
Requirement already satisfied: six>=1.5 in c:\programdata\anaconda3\envs\pythonproject\lib\site-packages (from python-dateutil>=2.8.2->pandas>=2.0.0->geopandas) (1.17.0)
Installing collected packages: shapely, pyproj, pyogrio, geopandas
Successfully installed geopandas-1.1.4 pyogrio-0.13.0 pyproj-3.7.1 shapely-2.1.2
Note: you may need to restart the kernel to use updated packages.

In [64]:
import geopandas as gpd

hex8 = gpd.read_file(
    f"s3://{BUCKET}/city-hex-polygons-8.geojson"
)

print("Rows:", len(hex8))
print("Columns:", len(hex8.columns))

Rows: 3832
Columns: 4

In [65]:
hex8.columns.tolist()

['index', 'centroid_lat', 'centroid_lon', 'geometry']

In [66]:
hex8.head()

,index,centroid_lat,centroid_lon,geometry
0,88ad361801fffff,-33.859427,18.677843,"POLYGON ((18.68119 -33.8633, 18.68357 -33.8592..."
1,88ad361803fffff,-33.855696,18.668766,"POLYGON ((18.67211 -33.85957, 18.6745 -33.8555..."
2,88ad361805fffff,-33.855263,18.685959,"POLYGON ((18.68931 -33.85914, 18.69169 -33.855..."
3,88ad361807fffff,-33.851532,18.676881,"POLYGON ((18.68023 -33.85541, 18.68261 -33.851..."
4,88ad361809fffff,-33.867322,18.678806,"POLYGON ((18.68215 -33.8712, 18.68454 -33.8671..."

In [67]:
print("Hexagons:", len(hex8))
print("Unique H3 indexes:", hex8["index"].nunique())
print("Missing H3 indexes:", hex8["index"].isna().sum())
print("Missing geometry:", hex8["geometry"].isna().sum())

Hexagons: 3832
Unique H3 indexes: 3832
Missing H3 indexes: 0
Missing geometry: 0

In [68]:
print("CRS:", hex8.crs)
print("Geometry types:")
print(hex8.geometry.geom_type.value_counts())

CRS: EPSG:4326
Geometry types:
Polygon    3832
Name: count, dtype: int64

Notes 
Hexagons:              3,832
Unique H3 indexes:     3,832
Missing H3 indexes:    0
Missing geometry:      0
CRS:                   EPSG:4326
Geometry type:         Polygon

we need tocheck if H3 resolution has json data lets checkit

In [69]:
response = s3.get_object(
    Bucket=BUCKET,
    Key="city-hex-polygons-8-10.geojson",
    Range="bytes=0-5000"
)

sample = response["Body"].read().decode("utf-8")

print(sample[:5000])

{
"type": "FeatureCollection",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "index": "88ad361801fffff", "centroid_lat": -33.859427322761434, "centroid_lon": 18.677843311941835, "resolution": 8 }, "geometry": { "type": "Polygon", "coordinates": [ [ [ 18.6811898997334, -33.863302790817968 ], [ 18.683574296194426, -33.85928287732969 ], [ 18.680227609989728, -33.85540739558428 ], [ 18.674496767706248, -33.855551865779326 ], [ 18.672112346191998, -33.859571723609463 ], [ 18.675458791982372, -33.863447166906802 ], [ 18.6811898997334, -33.863302790817968 ] ] ] } },
{ "type": "Feature", "properties": { "index": "88ad361803fffff", "centroid_lat": -33.855695953283139, "centroid_lon": 18.668766173796456, "resolution": 8 }, "geometry": { "type": "Polygon", "coordinates": [ [ [ 18.672112346191998, -33.859571723609463 ], [ 18.674496767706248, -33.855551865779326 ], [ 18.671150496788311, -33.851676081758441 ], [ 18.665420044866909, -33.851820194073497 ], [ 18.663035598432934, -33.855839996203308 ], [ 18.666381628808026, -33.859715741722489 ], [ 18.672112346191998, -33.859571723609463 ] ] ] } },
{ "type": "Feature", "properties": { "index": "88ad361805fffff", "centroid_lat": -33.855262542646564, "centroid_lon": 18.685958700425058, "resolution": 8 }, "geometry": { "type": "Polygon", "coordinates": [ [ [ 18.689305528598972, -33.859138049118094 ], [ 18.691689809315491, -33.855117645115939 ], [ 18.688342882830206, -33.851242124966504 ], [ 18.682611915876898, -33.851387047227377 ], [ 18.680227609989728, -33.85540739558428 ], [ 18.683574296194426, -33.85928287732969 ], [ 18.689305528598972, -33.859138049118094 ] ] ] } },
{ "type": "Feature", "properties": { "index": "88ad361807fffff", "centroid_lat": -33.851531586789342, "centroid_lon": 18.676881197083283, "resolution": 8 }, "geometry": { "type": "Polygon", "coordinates": [ [ [ 18.680227609989728, -33.85540739558428 ], [ 18.682611915876898, -33.851387047227377 ], [ 18.679265404549795, -33.847511224748857 ], [ 18.673534827712604, -33.847655789088989 ], [ 18.671150496788311, -33.851676081758441 ], [ 18.674496767706248, -33.855551865779326 ], [ 18.680227609989728, -33.85540739558428 ] ] ] } },
{ "type": "Feature", "properties": { "index": "88ad361809fffff", "centroid_lat": -33.86732228305511, "centroid_lon": 18.678805511098769, "resolution": 8 }, "geometry": { "type": "Polygon", "coordinates": [ [ [ 18.682152273791363, -33.871197410257686 ], [ 18.684536760831623, -33.867177931714707 ], [ 18.6811898997334, -33.863302790817968 ], [ 18.675458791982372, -33.863447166906802 ], [ 18.673074279872768, -33.867466589820921 ], [ 18.676420900551488, -33.871341692279181 ], [ 18.682152273791363, -33.871197410257686 ] ] ] } },
{ "type": "Feature", "properties": { "index": "88ad36180bfffff", "centroid_lat": -33.863591160223464, "centroid_lon": 18.669727932597294, "resolution": 8 }, "geometry": { "type": "Polygon", "coordinates": [ [ [ 18.673074279872768, -33.867466589820921 ], [ 18.675458791982372, -33.863447166906802 ], [ 18.672112346191998, -33.859571723609463 ], [ 18.666381628808026, -33.859715741722489 ], [ 18.663997091762614, -33.863735108965621 ], [ 18.667343297004926, -33.867610513770835 ], [ 18.673074279872768, -33.867466589820921 ] ] ] } },
{ "type": "Feature", "properties": { "index": "88ad36180dfffff", "centroid_lat": -33.863158031905506, "centroid_lon": 18.686921255628558, "resolution": 8 }, "geometry": { "type": "Polygon", "coordinates": [ [ [ 18.69026825870867, -33.867033197513507 ], [ 18.692652629982913, -33.863013228409287 ], [ 18.689305528598972, -33.859138049118094 ], [ 18.683574296194426, -33.85928287732969 ], [ 18.6811898997334, -33.863302790817968 ], [ 18.684536760831623, -33.867177931714707 ], [ 18.69026825870867, -33.867033197513507 ] ] ] } },
{ "type": "Feature", "properties": { "index": "88ad361811fffff", "centroid_lat": -33.856126934156201, "centroid_lon": 18.651575193690089, "resolution": 8 }, "geometry": { "type": "Polygon", "coordinates": [ [ [ 18.654920709809225, -33.860002968007123 ], [ 18.657305271656927, -33.85598365647715 ], [ 18.65395965680446, -33.852107608914913 ], [ 18.648229720877193, -33.852250911486216 ], [ 18.645845134360666, -33.856270167260895 ], [ 18.649190508408193, -33.860146176223694 ], [ 18.654920709809225, -33.860002968007123 ] ] ] } },
{ "type": "Feature", "properties": { "index": "88ad361813fffff", "centroid_lat": -33.852393831551474, "centroid_lon": 18.642500033980554, "resolution": 8 }, "geometry": { "type": "Polygon", "coordinates": [ [ [ 18.645845134360666, -33.856270167260895 ], [ 18.648229720877193, -33.852250911486216 ], [ 18.644884521654603, -33.848374562059767 ], [ 18.639154976816716, -33.848517507065239 ], [ 18.636770365764818, -33.852536707042518 ], [ 18.64011532405414, -33.856413017815818 ], [ 18.645845134360666, -33.856270167260895 ] ] ] } },
{ "type": "Feature", "properties": { "index": "88ad361815fffff", "centroid_lat": -33.851963923786002,