In [1]:
import boto3
import pandas as pd

BUCKET = "cct-ds-code-challenge-input-data"
REGION = "af-south-1"

s3 = boto3.client(
    "s3",
    region_name=REGION
)

In [9]:
import sys
import os

print("Python:")
print(sys.executable)

print("\nWorking directory:")
print(os.getcwd())

print("\nPython path:")
print("\n".join(sys.path))

Python:
c:\ProgramData\anaconda3\envs\pythonProject\python.exe

Working directory:
c:\Projects\City of Cape Town\Project\ds_code_challenge\notebooks

Python path:
c:\ProgramData\anaconda3\envs\pythonProject\python310.zip
c:\ProgramData\anaconda3\envs\pythonProject\DLLs
c:\ProgramData\anaconda3\envs\pythonProject\lib
c:\ProgramData\anaconda3\envs\pythonProject

c:\ProgramData\anaconda3\envs\pythonProject\lib\site-packages
c:\ProgramData\anaconda3\envs\pythonProject\lib\site-packages\win32
c:\ProgramData\anaconda3\envs\pythonProject\lib\site-packages\win32\lib
c:\ProgramData\anaconda3\envs\pythonProject\lib\site-packages\pythonwin

In [3]:

import sys

# 1. Tell Python to step up out of the notebooks folder so it can find 'src'
sys.path.insert(0, "..")
from src.extraction.s3_client import S3Client

s3 = S3Client()

sr = s3.read_csv("sr.csv.gz")

print(f"Rows: {len(sr):,}")
print(f"Columns: {len(sr.columns)}")

display(sr.head(10))

{'aws': {'region': 'af-south-1'}, 's3': {'bucket': 'cct-ds-code-challenge-input-data'}}
Rows: 941,634
Columns: 16

,Unnamed: 0,notification_number,reference_number,creation_timestamp,completion_timestamp,directorate,department,branch,section,code_group,code,cause_code_group,cause_code,official_suburb,latitude,longitude
0,0,400583534,9.109492e+09,2020-10-07 06:55:18+02:00,2020-10-08 15:36:35+02:00,URBAN MOBILITY,Roads Infrastructure Management,RIM Area Central,District: Blaauwberg,TD Customer complaint groups,Pothole&Defect Road Foot Bic Way/Kerbs,Road (RCL),Wear and tear,MONTAGUE GARDENS,-33.872839,18.522488
1,1,400555043,9.108995e+09,2020-07-09 16:08:13+02:00,2020-07-14 14:27:01+02:00,URBAN MOBILITY,Roads Infrastructure Management,RIM Area East,District : Somerset West,TD Customer complaint groups,Manhole Cover/Gully Grid,Road (RCL),Vandalism,SOMERSET WEST,-34.078916,18.848940
2,2,400589145,9.109614e+09,2020-10-27 10:21:59+02:00,2020-10-28 17:48:15+02:00,URBAN MOBILITY,Roads Infrastructure Management,RIM Area East,District : Somerset West,TD Customer complaint groups,Manhole Cover/Gully Grid,Road (RCL),Vandalism,STRAND,-34.102242,18.821116
3,3,400538915,9.108601e+09,2020-03-19 06:36:06+02:00,2021-03-29 20:34:19+02:00,URBAN MOBILITY,Roads Infrastructure Management,RIM Area North,District : Bellville,TD Customer complaint groups,Paint Markings Lines&Signs,Road Markings,Wear and tear,RAVENSMEAD,-33.920019,18.607209
4,4,400568554,NaN,2020-08-25 09:48:42+02:00,2020-08-31 08:41:13+02:00,URBAN MOBILITY,Roads Infrastructure Management,RIM Area South,District : Athlone,TD Customer complaint groups,Pothole&Defect Road Foot Bic Way/Kerbs,Road (RCL),Surfacing failure,CLAREMONT,-33.987400,18.453760
5,5,400556029,9.109003e+09,2020-07-11 10:34:37+02:00,2020-07-21 12:35:53+02:00,URBAN MOBILITY,Roads Infrastructure Management,RIM Area East,District : Somerset West,TD Customer complaint groups,Pothole&Defect Road Foot Bic Way/Kerbs,Road (RCL),Base failure,STRAND,-34.119520,18.829917
6,6,400588369,NaN,2020-10-23 10:33:48+02:00,2020-10-26 14:16:49+02:00,URBAN MOBILITY,Roads Infrastructure Management,RIM Area North,District : Bellville,TD Customer complaint groups,Pothole&Defect Road Foot Bic Way/Kerbs,NaN,NaN,GLENHAVEN,-33.917996,18.658031
7,7,400549080,NaN,2020-06-17 15:46:11+02:00,2020-11-24 14:26:09+02:00,URBAN MOBILITY,Roads Infrastructure Management,RIM Area North,District : Bellville,TD Customer complaint groups,Pothole&Defect Road Foot Bic Way/Kerbs,NaN,NaN,RAVENSMEAD,-33.922154,18.596821
8,8,400599701,9.109845e+09,2020-12-04 08:30:50+02:00,2020-12-14 12:53:52+02:00,URBAN MOBILITY,Roads Infrastructure Management,RIM Area Central,District: Cape Town,TD Customer complaint groups,Block Pipe/Chan/Canal/Drain/Gully/Manh,NaN,NaN,CAPE TOWN CITY CENTRE,-33.925721,18.421675
9,9,400569986,NaN,2020-08-28 13:37:53+02:00,2020-08-28 16:17:35+02:00,URBAN MOBILITY,Roads Infrastructure Management,RIM Area North,District : Kraaifontein,TD Customer complaint groups,Pothole&Defect Road Foot Bic Way/Kerbs,Road (RCL),Surfacing failure,DURBANVILLE,-33.835098,18.652708

In [6]:
import sys
sys.path.insert(0, "..")

from src.extraction.s3_client import S3Client

s3 = S3Client()

sr = s3.read_csv("sr.csv.gz")

print(f"Rows: {len(sr):,}")
print(f"Columns: {len(sr.columns)}")

Rows: 941,634
Columns: 16

In [7]:
response = s3.select_object_content(
    Bucket=BUCKET,
    Key="city-hex-polygons-8-10.geojson",
    ExpressionType="SQL",
    Expression="""
        SELECT *
        FROM S3Object
    """,
    InputSerialization={
        "JSON": {
            "Type": "DOCUMENT"
        }
    },
    OutputSerialization={
        "JSON": {
            "RecordDelimiter": "\n"
        }
    }
)

records = []

for event in response["Payload"]:
    if "Records" in event:
        records.append(event["Records"]["Payload"])

result = b"".join(records).decode("utf-8")

print(result[:2000])

AttributeError: 'S3Client' object has no attribute 'select_object_content'

In [8]:
import sys
sys.path.insert(0, "..")

import src.extraction.s3_client as client

print(client.config)
print(type(client.config))

{'aws': {'region': 'af-south-1'}, 's3': {'bucket': 'cct-ds-code-challenge-input-data'}}
<class 'dict'>

In [9]:
import sys
sys.path.insert(0, "..")

from src.extraction.s3_client import S3Client

s3 = S3Client()

In [1]:
import sys
sys.path.insert(0, "..")

from src.extraction.s3_client import S3Client

s3 = S3Client()

{'aws': {'region': 'af-south-1'}, 's3': {'bucket': 'cct-ds-code-challenge-input-data'}}

In [2]:
print(hasattr(s3, "select_json"))

True

In [3]:
import json

response = s3.client.get_object(
    Bucket=s3.bucket,
    Key="city-hex-polygons-8-10.geojson"
)

geojson = json.loads(response["Body"].read())

print(geojson.keys())
print(geojson["features"][0])

dict_keys(['type', 'crs', 'features'])
{'type': 'Feature', 'properties': {'index': '88ad361801fffff', 'centroid_lat': -33.859427322761434, 'centroid_lon': 18.677843311941835, 'resolution': 8}, 'geometry': {'type': 'Polygon', 'coordinates': [[[18.6811898997334, -33.86330279081797], [18.683574296194426, -33.85928287732969], [18.68022760998973, -33.85540739558428], [18.67449676770625, -33.855551865779326], [18.672112346191998, -33.85957172360946], [18.675458791982372, -33.8634471669068], [18.6811898997334, -33.86330279081797]]]}}

In [1]:
import sys
sys.path.insert(0, "..")

from src.extraction.s3_client import S3Client

s3 = S3Client()

{'aws': {'region': 'af-south-1'}, 's3': {'bucket': 'cct-ds-code-challenge-input-data'}}

read the geo jason

In [2]:
import json

raw = s3.read_geojson(
    "city-hex-polygons-8-10.geojson"
)

geojson = json.loads(raw)

print(geojson["type"])
print(len(geojson["features"]))

FeatureCollection
203840

extract only H3 resolution 8

In [3]:
features_8 = [
    feature
    for feature in geojson["features"]
    if feature["properties"]["resolution"] == 8
]

print(f"H3 level 8 features: {len(features_8):,}")

H3 level 8 features: 3,832

In [5]:
import pandas as pd

In [6]:
h3_df = pd.DataFrame([
    {
        "h3_index": f["properties"]["index"],
        "centroid_lat": f["properties"]["centroid_lat"],
        "centroid_lon": f["properties"]["centroid_lon"],
        "resolution": f["properties"]["resolution"],
        "geometry": f["geometry"],
    }
    for f in features_8
])

print(h3_df.shape)
display(h3_df.head())

(3832, 5)

,h3_index,centroid_lat,centroid_lon,resolution,geometry
0,88ad361801fffff,-33.859427,18.677843,8,"{'type': 'Polygon', 'coordinates': [[[18.68118..."
1,88ad361803fffff,-33.855696,18.668766,8,"{'type': 'Polygon', 'coordinates': [[[18.67211..."
2,88ad361805fffff,-33.855263,18.685959,8,"{'type': 'Polygon', 'coordinates': [[[18.68930..."
3,88ad361807fffff,-33.851532,18.676881,8,"{'type': 'Polygon', 'coordinates': [[[18.68022..."
4,88ad361809fffff,-33.867322,18.678806,8,"{'type': 'Polygon', 'coordinates': [[[18.68215..."